pipeline {
    agent any

    stages {
        stage('Create venv') {
            steps {
                sh 'python3 -m venv venv'
            }
        }
        stage('Install dependencies') {
            steps {
                sh '''
                    . venv/bin/activate
                    pip install -r PyTest_Introduction/requirements.txt
                '''
            }
        }
        stage('Run tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest
                '''
            }
        }
    }
}